<!DOCTYPE html>
<html>
<head>
  <title>Swagger UI</title>
  <link href='https://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css'/>
  <link href='<?php echo $this->basePath('swagger-ui/css/highlight.default.css'); ?>' media='screen' rel='stylesheet' type='text/css'/>
  <link href='<?php echo $this->basePath('swagger-ui/css/screen.css'); ?>' media='screen' rel='stylesheet' type='text/css'/>
  <script type="text/javascript" src="<?php echo $this->basePath('swagger-ui/lib/shred.bundle.js'); ?>"></script>
  <script src='<?php echo $this->basePath('swagger-ui/lib/jquery-1.8.0.min.js'); ?>' type='text/javascript'></script>
  <script src='<?php echo $this->basePath('swagger-ui/lib/jquery.slideto.min.js'); ?>' type='text/javascript'></script>
  <script src='<?php echo $this->basePath('swagger-ui/lib/jquery.wiggle.min.js'); ?>' type='text/javascript'></script>
  <script src='<?php echo $this->basePath('swagger-ui/lib/jquery.ba-bbq.min.js'); ?>' type='text/javascript'></script>
  <script src='<?php echo $this->basePath('swagger-ui/lib/handlebars-1.0.0.js'); ?>' type='text/javascript'></script>
  <script src='<?php echo $this->basePath('swagger-ui/lib/underscore-min.js'); ?>' type='text/javascript'></script>
  <script src='<?php echo $this->basePath('swagger-ui/lib/backbone-min.js'); ?>' type='text/javascript'></script>
  <script src='<?php echo $this->basePath('swagger-ui/lib/swagger.js'); ?>' type='text/javascript'></script>
  <script src='<?php echo $this->basePath('swagger-ui/js/swagger-ui.js'); ?>' type='text/javascript'></script>
  <script src='<?php echo $this->basePath('swagger-ui/lib/highlight.7.3.pack.js'); ?>' type='text/javascript'></script>
  <script type="text/javascript">
    $(function () {
      window.swaggerUi = new SwaggerUi({
      url: "<?php echo $this->swaggerUrl; ?>",
      dom_id: "swagger-ui-container",
      supportedSubmitMethods: ['get', 'post', 'put', 'delete'],
      onComplete: function(swaggerApi, swaggerUi){
        log("Loaded SwaggerUI")
        $('pre code').each(function(i, e) {hljs.highlightBlock(e)});
      },
      onFailure: function(data) {
        log("Unable to Load SwaggerUI");
      },
      docExpansion: "none"
    });

    $('#input_apiKey').change(function() {
      var key = $('#input_apiKey')[0].value;
      log("key: " + key);
      if(key && key.trim() != "") {
        log("added key " + key);
        window.authorizations.add("key", new ApiKeyAuthorization("api_key", key, "query"));
      }
    })
    window.swaggerUi.load();
  });

  </script>
  <style type="text/css">
    #header {
      background: url(/swagger-ui/images/header-menu-bg.png) repeat-x;
      border-bottom: 0;
    }
  </style>
</head>

<body>
<div id='header'>
  <div class="swagger-ui-wrap">
    <img src="/swagger-ui/images/logo.png" title="Api Melhor Menu" style="margin-top: -10px">
  </div>
</div>

<div id="message-bar" class="swagger-ui-wrap">
  &nbsp;
</div>

<div id="swagger-ui-container" class="swagger-ui-wrap">

</div>

</body>

</html>
